### ISSUE TITLE
Why is a bandpass filter used instead of a MWA?

### ISSUE THREAD

**Issue by maxxu05** [berndporr/py-ecg-detectors#19]
I was reading the source code and noticed that in the SWT detector, a bandpass filter is used after the doubling, instead of a moving window average, which is what they described in their paper. Is there a particular reason for this?

**Comment by berndporr** [comment]
You are right. I guess Luis has put a bandpass in there to improve the performance as with the moving average it's actually pretty bad. See the "usage_example.py" and use the wavelet detector. However, to reproduce the publication it indeed needs to be a moving average so that's now implemented. Also the max duration of the QRS complex now matches exactly the publication. That was a bit shorter in the code. Thanks for spotting it.
https://github.com/berndporr/py-ecg-detectors/commit/94df9184fcdcd3de01fa03e8e0c5a566fb146b19
